name: inclass12
description: "Inventory Management App with Firebase"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'  

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.18.0
  cloud_firestore: ^4.9.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutterfire_cli: ^1.1.0

flutter:
  uses-material-design: true
