// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDZ_IOYg6qQaKwfvC2PPCETwMC_z558Ug',
    appId: '1:85984333857:web:bd1e669d5c258bfc0ad360',
    messagingSenderId: '85984333857',
    projectId: 'flutterfirebasedemo88',
    authDomain: 'flutterfirebasedemo88.firebaseapp.com',
    storageBucket: 'flutterfirebasedemo88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrFqgsdih_LCA0S_NvGAg2I6kPDRfp65o',
    appId: '1:85984333857:android:cdea0053fc2b387a0ad360',
    messagingSenderId: '85984333857',
    projectId: 'flutterfirebasedemo88',
    storageBucket: 'flutterfirebasedemo88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY3O77HDuRLxl4BOThNfvSBYZD2E93TyE',
    appId: '1:85984333857:ios:8af5151b114b42a60ad360',
    messagingSenderId: '85984333857',
    projectId: 'flutterfirebasedemo88',
    storageBucket: 'flutterfirebasedemo88.firebasestorage.app',
    iosBundleId: 'com.example.inclass12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY3O77HDuRLxl4BOThNfvSBYZD2E93TyE',
    appId: '1:85984333857:ios:8af5151b114b42a60ad360',
    messagingSenderId: '85984333857',
    projectId: 'flutterfirebasedemo88',
    storageBucket: 'flutterfirebasedemo88.firebasestorage.app',
    iosBundleId: 'com.example.inclass12',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDZ_IOYg6qQaKwfvC2PPCETwMC_z558Ug',
    appId: '1:85984333857:web:7c5df5d8beb814500ad360',
    messagingSenderId: '85984333857',
    projectId: 'flutterfirebasedemo88',
    authDomain: 'flutterfirebasedemo88.firebaseapp.com',
    storageBucket: 'flutterfirebasedemo88.firebasestorage.app',
  );

}